This notebook will see how different features are related and select the features that are most relevant and less redundant

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sys
pd.set_option('display.max_columns', None)

In [8]:
# !pip install minepy
# !pip install numpy Cython
# !pip install pymrmr

In [29]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [31]:
df = pd.read_pickle("cleanDataDraft1.pkl")

In [35]:
# df.info()

In [36]:
df.dropna(inplace=True)
# df.info()

In [37]:
X = df.drop("hiedinch", axis=1).values
Y = df[["hiedinch"]].values

In [62]:
test = SelectKBest(score_func=chi2)
model = test.fit(X, Y)
np.set_printoptions(precision = 3)
score = model.scores_
features = model.transform(X)
columns = df.drop("hiedinch", axis=1).columns

In [63]:
df_feature_score1 = pd.DataFrame({"Features": columns, "Score": score})
df_feature_score1.sort_values(by="Score", ascending=False)

           Features         Score
22         estimate  9.655447e+07
17          lotsize  3.555101e+06
11           medinc  3.168790e+05
12            nsqft  1.232819e+05
3               age  3.271201e+03
2             child  2.484090e+03
4             birth  5.309801e+02
1           mstatus  4.696379e+02
15           nrooms  2.168564e+02
13           nbaths  1.089232e+02
14            nbeds  9.973143e+01
7               veh  9.394411e+01
25            mtgds  7.554630e+01
31            asian  7.156787e+01
16          stories  5.084614e+01
21          yrbuilt  4.739851e+01
23          purchyr  2.822297e+01
19           garage  6.354271e+00
30  american_indian  4.425285e+00
20            sewer  3.773352e+00
8              sloc  3.338184e+00
10         nbhdrate  3.184222e+00
29            black  2.473821e+00
0               sex  1.681102e+00
28            white  1.433411e+00
6               own  1.177838e+00
9         dwellrate  8.713955e-01
32         hawaiian  8.642454e-01
26            heloc  7.903840e-01
24             mtgd  7.750763e-01
18            condo  7.675272e-01
5                sp  3.726131e-01
27           helump  9.692159e-03

Using PCA

In [69]:
from sklearn.decomposition import PCA

In [71]:
pca = PCA(n_components=10)
model = pca.fit(X)
print("Explained Variances: %s" % model.explained_variance_ratio_)

Explained Variances: [7.627e-01 2.359e-01 1.347e-03 5.641e-05 1.008e-07 6.827e-09 3.062e-09
 6.891e-10 7.441e-11 3.716e-11]

Using Random Forest and Extra Trees

In [74]:
from sklearn.ensemble import ExtraTreesClassifier

model = ExtraTreesClassifier(n_estimators=10)
model.fit(X, Y)
score = model.feature_importances_

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

In [75]:
df_feature_score2 = pd.DataFrame({"Features": columns, "Score": score})
df_feature_score2.sort_values(by="Score", ascending=False)

           Features     Score
2             child  0.152673
3               age  0.099388
22         estimate  0.059468
23          purchyr  0.044692
12            nsqft  0.043044
15           nrooms  0.042122
11           medinc  0.039460
21          yrbuilt  0.037129
1           mstatus  0.036977
10         nbhdrate  0.035764
24             mtgd  0.034023
17          lotsize  0.033543
16          stories  0.032381
7               veh  0.031630
13           nbaths  0.031024
8              sloc  0.029241
14            nbeds  0.028635
9         dwellrate  0.028117
25            mtgds  0.025406
0               sex  0.020254
4             birth  0.017833
6               own  0.015755
5                sp  0.012567
20            sewer  0.010980
19           garage  0.009202
26            heloc  0.009188
31            asian  0.008605
28            white  0.008020
29            black  0.007110
27           helump  0.006901
18            condo  0.006312
30  american_indian  0.001328
32         hawaiian  0.001230

In [78]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
model = LogisticRegression(solver="lbfgs")

rfe = RFE(model, 10)
fit = rfe.fit(X, Y)
# print(fit.n_features_)
# print(fit.support_)
rank = fit.ranking_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

In [79]:
df_feature_score3 = pd.DataFrame({"Features": columns, "Score": rank})
df_feature_score3.sort_values(by="Score", ascending=True)

           Features  Score
0               sex      1
1           mstatus      1
2             child      1
30  american_indian      1
20            sewer      1
5                sp      1
19           garage      1
31            asian      1
15           nrooms      1
13           nbaths      1
14            nbeds      2
10         nbhdrate      3
16          stories      4
6               own      5
25            mtgds      6
26            heloc      7
3               age      8
7               veh      9
8              sloc     10
9         dwellrate     11
24             mtgd     12
28            white     13
18            condo     14
29            black     15
21          yrbuilt     16
23          purchyr     17
4             birth     18
12            nsqft     19
11           medinc     20
32         hawaiian     21
27           helump     22
22         estimate     23
17          lotsize     24